#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 5.4
#  in conjunction with Tcl version 8.6
#    Sep 12, 2020 08:18:16 PM -03  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk

    py3 = False
except ImportError:
    import tkinter.ttk as ttk

    py3 = True

import lexico_support
from Lexico import Lexico

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = InterfaceLexico(root)
    lexico_support.init(root, top)
    root.mainloop()


w = None


def create_Toplevel1(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_Toplevel1(root, *args, **kwargs)' .'''
    global w, w_win, root
    # rt = root
    root = rt
    w = tk.Toplevel(root)
    top = InterfaceLexico(w)
    lexico_support.init(w, top, *args, **kwargs)
    return (w, top)


def destroy_Toplevel1():
    global w
    w.destroy()
    w = None


class InterfaceLexico:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9'  # X11 color: 'gray85'
        _ana1color = '#d9d9d9'  # X11 color: 'gray85'
        _ana2color = '#ececec'  # Closest X11 color: 'gray92'

        self.lexico = Lexico()

        top.geometry("1562x965+310+8")
        top.minsize(148, 1)
        top.maxsize(4804, 1325)
        top.resizable(1, 1)
        top.title("Lexico Simulador")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.007, rely=0.01, relheight=0.058, relwidth=0.984)

        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(cursor="fleur")

        self.title_lexico = tk.Label(self.Frame1)
        self.title_lexico.place(relx=0.423, rely=0.179, height=30 ,width=150)
        self.title_lexico.configure(background="#d9d9d9")
        self.title_lexico.configure(disabledforeground="#a3a3a3")
        self.title_lexico.configure(foreground="#000000")
        self.title_lexico.configure(text='''Lexico''')
        self.title_lexico.configure(fg="navy blue")
        self.title_lexico.configure(font="Helvetica 16 bold")

        self.Frame2 = tk.Frame(top)
        self.Frame2.place(relx=0.006, rely=0.073, relheight=0.821, relwidth=0.677)
        self.Frame2.configure(relief='groove')
        self.Frame2.configure(borderwidth="2")
        self.Frame2.configure(relief="groove")
        self.Frame2.configure(background="#d9d9d9")

        self.title_programa = tk.Label(self.Frame2)
        self.title_programa.place(relx=0.407, rely=0.013, height=26, width=150)
        self.title_programa.configure(background="#d9d9d9")
        self.title_programa.configure(disabledforeground="#a3a3a3")
        self.title_programa.configure(foreground="#000000")
        self.title_programa.configure(text='''Programa''')
        self.title_programa.configure(fg="navy blue")
        self.title_programa.configure(font="Helvetica 16 bold")

        self.Listbox_programa = tk.Listbox(self.Frame2)
        self.Listbox_programa.place(relx=0.011, rely=0.064, relheight=0.926, relwidth=0.974)
        self.Listbox_programa.configure(background="white")
        self.Listbox_programa.configure(disabledforeground="#a3a3a3")
        self.Listbox_programa.configure(font="TkFixedFont")
        self.Listbox_programa.configure(foreground="#000000")

        self.Frame3 = tk.Frame(top)
        self.Frame3.place(relx=0.685, rely=0.073, relheight=0.818, relwidth=0.304)
        self.Frame3.configure(relief='groove')
        self.Frame3.configure(borderwidth="2")
        self.Frame3.configure(relief="groove")
        self.Frame3.configure(background="#d9d9d9")

        self.title_lexema = tk.Label(self.Frame3)
        self.title_lexema.place(relx=0.163, rely=0.013, height=26, width=153)
        self.title_lexema.configure(background="#d9d9d9")
        self.title_lexema.configure(disabledforeground="#a3a3a3")
        self.title_lexema.configure(foreground="#000000")
        self.title_lexema.configure(text='''Lexema''')
        self.title_lexema.configure(fg="navy blue")
        self.title_lexema.configure(font="Helvetica 16 bold")

        self.title_simbolo = tk.Label(self.Frame3)
        self.title_simbolo.place(relx=0.470, rely=0.013, height=26, width=197)
        self.title_simbolo.configure(background="#d9d9d9")
        self.title_simbolo.configure(disabledforeground="#a3a3a3")
        self.title_simbolo.configure(foreground="#000000")
        self.title_simbolo.configure(text='''Simbolo''')
        self.title_simbolo.configure(fg="navy blue")
        self.title_simbolo.configure(font="Helvetica 16 bold")

        self.Listbox_lexema = tk.Listbox(self.Frame3)
        self.Listbox_lexema.place(relx=0.147, rely=0.063, relheight=0.925, relwidth=0.358)
        self.Listbox_lexema.configure(background="white")
        self.Listbox_lexema.configure(disabledforeground="#a3a3a3")
        self.Listbox_lexema.configure(font="TkFixedFont")
        self.Listbox_lexema.configure(foreground="#000000")
        self.Listbox_lexema.bind("<MouseWheel>", self.OnMouseWheel)

        self.Listbox_simbolo = tk.Listbox(self.Frame3)
        self.Listbox_simbolo.place(relx=0.505, rely=0.063, relheight=0.924, relwidth=0.358)
        self.Listbox_simbolo.configure(background="white")
        self.Listbox_simbolo.configure(disabledforeground="#a3a3a3")
        self.Listbox_simbolo.configure(font="TkFixedFont")
        self.Listbox_simbolo.configure(foreground="#000000")
        self.Listbox_simbolo.bind("<MouseWheel>", self.OnMouseWheel)

        self.Button_carregar = tk.Button(top)
        self.Button_carregar.place(relx=0.09, rely=0.912, height=53, width=216)
        self.Button_carregar.configure(activebackground="#ececec")
        self.Button_carregar.configure(activeforeground="#000000")
        self.Button_carregar.configure(background="#d9d9d9")
        self.Button_carregar.configure(disabledforeground="#a3a3a3")
        self.Button_carregar.configure(foreground="#000000")
        self.Button_carregar.configure(highlightbackground="#d9d9d9")
        self.Button_carregar.configure(highlightcolor="black")
        self.Button_carregar.configure(pady="0")
        self.Button_carregar.configure(text='''CARREGAR''')
        self.Button_carregar.configure(fg="black")
        self.Button_carregar.configure(font="Arial 12")
        self.Button_carregar.configure(command=self.le_arquivo)

        self.Button_run = tk.Button(top)
        self.Button_run.place(relx=0.237, rely=0.912, height=53, width=216)
        self.Button_run.configure(activebackground="#ececec")
        self.Button_run.configure(activeforeground="#000000")
        self.Button_run.configure(background="#d9d9d9")
        self.Button_run.configure(disabledforeground="#a3a3a3")
        self.Button_run.configure(foreground="#000000")
        self.Button_run.configure(highlightbackground="#d9d9d9")
        self.Button_run.configure(highlightcolor="black")
        self.Button_run.configure(pady="0")
        self.Button_run.configure(text='''RUN''')
        self.Button_run.configure(fg="black")
        self.Button_run.configure(font="Arial 12")
        self.Button_run.configure(command=self.inicia_lexico)

    #rolagem de todos os listboxes
    def OnMouseWheel(self, event):
        self.Listbox_lexema.yview_scroll(int(-1*(event.delta/120)),"units")
        self.Listbox_simbolo.yview_scroll(int(-1*(event.delta/120)),"units")
        return "break"

    def le_arquivo(self):
        self.Listbox_programa.delete(0, tk.END)
        self.Listbox_lexema.delete(0, tk.END)
        self.Listbox_simbolo.delete(0, tk.END)
        self.lexico.le_arquivo()
        for i, linha in enumerate(self.lexico.txt_arquivo.split('\n')):
            self.Listbox_programa.insert(i, linha)

    def inicia_lexico(self):
        self.lexico.inicia_lexico()
        for i, item in enumerate(self.lexico.lexemas_simbolos):
            self.Listbox_lexema.insert(i, item["lexema"])
            self.Listbox_simbolo.insert(i, item["simbolo"])


if __name__ == '__main__':
    vp_start_gui()
